##################################
# Qt Component utility function
##################################

function(qtx_check_component_available qt_component qt_version)
	set(COMPONENT_AVAILABLE True)
	if (${qt_component} STREQUAL "QmlMeta" AND ${qt_version} VERSION_LESS "6.8")
		set(COMPONENT_AVAILABLE False)
	endif()
	if (${qt_component}  STREQUAL "QuickControls2Basic" AND ${qt_version} VERSION_LESS "6.7")
		set(COMPONENT_AVAILABLE False)
	endif()
	if (${qt_component}  STREQUAL "QuickControls2BasicStyleImpl" AND ${qt_version} VERSION_LESS "6.7")
		set(COMPONENT_AVAILABLE False)
	endif()
	if (${qt_component}  STREQUAL "QuickControls2Material" AND ${qt_version} VERSION_LESS "6.7")
		set(COMPONENT_AVAILABLE False)
	endif()
	if (${qt_component}  STREQUAL "QuickControls2MaterialStyleImpl" AND ${qt_version} VERSION_LESS "6.7")
		set(COMPONENT_AVAILABLE False)
	endif()
	if (${qt_component}  STREQUAL "QuickEffectsPrivate" AND ${qt_version} VERSION_LESS "6.5")
		set(COMPONENT_AVAILABLE False)
	endif()
	set(QTX_COMPONENT_${qt_component}_AVAILABLE ${COMPONENT_AVAILABLE} PARENT_SCOPE)
endfunction()

function(qtx_get_lib_name qt_component qt_libname)
	set(LIB_NAME ${qt_component})
	if (${qt_component} STREQUAL "QuickEffectsPrivate")
		set(LIB_NAME "QuickEffects")
	elseif (${qt_component} STREQUAL "QuickShapesPrivate")
		set(LIB_NAME "QuickShapes")
	elseif (${qt_component} STREQUAL "QuickDialogs2")
		set(LIB_NAME "QuickDialogs2")
	endif()
	set(${qt_libname} ${LIB_NAME} PARENT_SCOPE)
endfunction()

# Function to filter component depending on Qt version used
function(qtx_filter_components qt_initial_components qt_version QT_COMPONENTS)
	set(TMP_QT_COMPONENTS "")
	foreach(module ${qt_initial_components})
		qtx_check_component_available(${module} ${qt_version})
		if(QTX_COMPONENT_${module}_AVAILABLE)
			list(APPEND TMP_QT_COMPONENTS "${module}")
		else()
			message(STATUS "Qt component ${module} excluded for Qt version: ${qt_version}")
		endif()
	endforeach()
	set(${QT_COMPONENTS} "${TMP_QT_COMPONENTS}" PARENT_SCOPE)
endfunction()

##################################
# QML utility function
##################################

# Get QML module files directory
function(qt_qml_module_directory qml_module qml_module_dir)
	if(${qml_module} STREQUAL "qtquick2")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_module_dir} "QtQuick" PARENT_SCOPE)
		else()
			set(${qml_module_dir} "QtQuick.2" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-layouts")
		set(${qml_module_dir} "QtQuick/Layouts" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-controls")
		set(${qml_module_dir} "QtQuick/Controls" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-dialogs")
		set(${qml_module_dir} "QtQuick/Dialogs" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-dialogs/private")
		set(${qml_module_dir} "QtQuick/Dialogs/Private" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-controls2")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_module_dir} "QtQuick/Controls" PARENT_SCOPE)
		else()
			set(${qml_module_dir} "QtQuick/Controls.2" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-controls2/material")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_module_dir} "QtQuick/Controls/Material" PARENT_SCOPE)
		else()
			set(${qml_module_dir} "QtQuick/Controls.2/Material" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-privatewidgets")
		set(${qml_module_dir} "QtQuick/PrivateWidgets" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-shapes")
		set(${qml_module_dir} "QtQuick/Shapes" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-window2")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_module_dir} "QtQuick/Window" PARENT_SCOPE)
		else()
			set(${qml_module_dir} "QtQuick/Window.2" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-templates2")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_module_dir} "QtQuick/Templates" PARENT_SCOPE)
		else()
			set(${qml_module_dir} "QtQuick/Templates.2" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtgraphicaleffects")
		set(${qml_module_dir} "QtGraphicalEffects" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtgraphicaleffects/private")
		set(${qml_module_dir} "QtGraphicalEffects/private" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtlocation")
		set(${qml_module_dir} "QtLocation" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtpositioning")
		set(${qml_module_dir} "QtPositioning" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtqml-models2")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_module_dir} "QtQml/Models" PARENT_SCOPE)
		else()
			set(${qml_module_dir} "QtQml/Models.2" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qt-labs-folderlistmodel")
		set(${qml_module_dir} "Qt/labs/folderlistmodel" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qt-labs-platform")
		set(${qml_module_dir} "Qt/labs/platform" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qt-labs-settings")
		set(${qml_module_dir} "Qt/labs/settings" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qt-labs-qmlmodels")
		set(${qml_module_dir} "Qt/labs/qmlmodels" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtqml-workerscript")
		set(${qml_module_dir} "QtQml/WorkerScript" PARENT_SCOPE)
	endif()
endfunction(qt_qml_module_directory)

# Get QML module plugin name
function(qt_qml_check_module_available qml_module qt_version qml_module_available)
	set(MODULE_AVAILABLE True)
	if (${qml_module} STREQUAL "qtquick-privatewidgets" AND ${QT_USE_VERSION} GREATER_EQUAL 6)
		set(MODULE_AVAILABLE False)
	endif()
	if (${qml_module} STREQUAL "qtquick-dialogs/private" AND ${QT_USE_VERSION} GREATER_EQUAL 6)
		set(MODULE_AVAILABLE False)
	endif()
	if (${qml_module} STREQUAL "qtgraphicaleffects" AND ${QT_USE_VERSION} GREATER_EQUAL 6)
		set(MODULE_AVAILABLE False)
	endif()
	if (${qml_module} STREQUAL "qtgraphicaleffects/private" AND ${QT_USE_VERSION} GREATER_EQUAL 6)
		set(MODULE_AVAILABLE False)
	endif()
	set(${qml_module_available} ${MODULE_AVAILABLE} PARENT_SCOPE)
endfunction()

function(qt_qml_module_plugin_name qml_module qml_plugin_name)
	if(${qml_module} STREQUAL "qtquick2")
		set(${qml_plugin_name} "qtquick2plugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-layouts")
		set(${qml_plugin_name} "qquicklayoutsplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-controls")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_plugin_name} "qtquickcontrols2plugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "qtquickcontrolsplugin" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-dialogs")
		if(QT_VERSION VERSION_LESS "6.8")
			set(${qml_plugin_name} "qtquickdialogsplugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "dialogplugin" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-dialogs/private")
		set(${qml_plugin_name} "dialogsprivateplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-controls2")
		set(${qml_plugin_name} "qtquickcontrols2plugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-controls2/material")
		if(${QT_VERSION_MAJOR} GREATER_EQUAL 6)
			set(${qml_plugin_name} "qtquickcontrols2materialstyleplugin" PARENT_SCOPE)
		elseif(MODULE_Qt${QT_VERSION_MAJOR}_VERSION VERSION_LESS 5.15.3)
			set(${qml_plugin_name} "qtquickcontrols2materialstyleplugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "qqc2materialstyleplugin" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-privatewidgets")
		set(${qml_plugin_name} "widgetsplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-shapes")
		set(${qml_plugin_name} "qmlshapesplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtquick-window2")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_plugin_name} "quickwindowplugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "windowplugin" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtquick-templates2")
		set(${qml_plugin_name} "qtquicktemplates2plugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtgraphicaleffects")
		set(${qml_plugin_name} "qtgraphicaleffectsplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtgraphicaleffects/private")
		set(${qml_plugin_name} "qtgraphicaleffectsprivate" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtlocation")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_plugin_name} "declarative_locationplugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "declarative_location" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtpositioning")
		if(QT_USE_VERSION EQUAL 6)
			set(${qml_plugin_name} "positioningquickplugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "declarative_positioning" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qtqml-models2")
		set(${qml_plugin_name} "modelsplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qt-labs-folderlistmodel")
		set(${qml_plugin_name} "qmlfolderlistmodelplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qt-labs-platform")
		if(${MODULE_Qt6_VERSION}} VERSION_LESS "6.8")
			set(${qml_plugin_name} "qtlabsplatformplugin" PARENT_SCOPE)
		else()
			set(${qml_plugin_name} "labsplatformplugin" PARENT_SCOPE)
		endif()
	elseif(${qml_module} STREQUAL "qt-labs-settings")
		set(${qml_plugin_name} "qmlsettingsplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qt-labs-qmlmodels")
		set(${qml_plugin_name} "labsmodelsplugin" PARENT_SCOPE)
	elseif(${qml_module} STREQUAL "qtqml-workerscript")
		set(${qml_plugin_name} "workerscriptplugin" PARENT_SCOPE)
	endif()
endfunction(qt_qml_module_plugin_name)

# Get QML module has package
function(qt_qml_module_has_package qml_module qml_has_package)
	if(${qml_module} MATCHES ".*/.*")
		set(${qml_has_package} FALSE PARENT_SCOPE)
	else()
		set(${qml_has_package} TRUE PARENT_SCOPE)
	endif()
endfunction(qt_qml_module_has_package)

# Get QML module has package
function(qt_qml_module_has_plugins_qmltypes qml_module qml_has_plugins_qmltypes)
	if(${qml_module} MATCHES ".*/private")
		set(${qml_has_plugins_qmltypes} FALSE PARENT_SCOPE)
	else()
		set(${qml_has_plugins_qmltypes} TRUE PARENT_SCOPE)
	endif()
endfunction(qt_qml_module_has_plugins_qmltypes)

##################################
# Install files utility function
##################################

# Install qt component

function(install_qt_dll qt_dll_dir qt_component qt_version_major install_path)
	if(QT_USE_VERSION LESS 5)
		INSTALL(FILES "${qt_dll_dir}/${qt_component}${qt_version_major}.dll"
				DESTINATION ${install_path} CONFIGURATIONS Release)
		INSTALL(FILES "${qt_dll_dir}/${qt_component}d${qt_version_major}.dll"
				DESTINATION ${install_path} CONFIGURATIONS Debug)
	elseif(QT_USE_DEBUG_DLL)
		INSTALL(FILES "${qt_dll_dir}/Qt${qt_version_major}${qt_component}.dll"
				DESTINATION ${install_path} CONFIGURATIONS Release)
		INSTALL(FILES "${qt_dll_dir}/Qt${qt_version_major}${qt_component}d.dll"
				DESTINATION ${install_path} CONFIGURATIONS Debug)
	else()
		INSTALL(FILES "${qt_dll_dir}/Qt${qt_version_major}${qt_component}.dll"
				DESTINATION ${install_path})
	endif()
endfunction()

# Install qt plugin

function(install_qt_plugins_directory category)
	set(SRC_DIR ${QT_PLUGINS_DIR}/${category})
	set(DST_DIR ${INSTALL_PATH_QTPLUGINS})
	install(DIRECTORY "${SRC_DIR}" DESTINATION ${DST_DIR})
endfunction(install_qt_plugins_directory)

function(install_qt_plugins_dll qt_dll_dir qt_component qt_version_major install_path)
	if(QT_USE_DEBUG_DLL)
		INSTALL(FILES "${qt_dll_dir}/${qt_component}.dll"
				DESTINATION ${install_path} CONFIGURATIONS Release)
		INSTALL(FILES "${qt_dll_dir}/${qt_component}d.dll"
				DESTINATION ${install_path} CONFIGURATIONS Debug)
	else()
		INSTALL(FILES "${qt_dll_dir}/${qt_component}.dll"
				DESTINATION ${install_path})
	endif()
endfunction()

function(install_qt_plugins category components)
	set(SRC_DIR ${QT_PLUGINS_DIR}/${category})
	set(DST_DIR ${INSTALL_PATH_QTPLUGINS}/${category})
	foreach(TMP_COMPONENT ${components})
		message(STATUS "QT plugins installing: ${category} => ${components}")
		if (WIN32)
			install_qt_plugins_dll(${SRC_DIR} ${TMP_COMPONENT} ${QT_VERSION_MAJOR} ${DST_DIR})
		elseif(APPLE)
			install(FILES "${SRC_DIR}/lib${TMP_COMPONENT}.dylib" DESTINATION ${DST_DIR})
			if(EXISTS "${SRC_DIR}/lib${TMP_COMPONENT}_debug.dylib")
				install(FILES "${SRC_DIR}/lib${TMP_COMPONENT}_debug.dylib" DESTINATION ${DST_DIR} CONFIGURATIONS Debug)
			endif()
		else()
			if(AUTONOMOUS_PACKAGE_BUILD)
				install(FILES "${SRC_DIR}/lib${TMP_COMPONENT}.so" DESTINATION ${DST_DIR})
			endif()
		endif()
	endforeach(TMP_COMPONENT)
endfunction(install_qt_plugins)

# Install qt qm files

macro(install_qm_files qm_files_path qm_modules langs install_path)
	foreach(qm_module ${qm_modules})
		foreach(lang ${langs})
			file(GLOB FILES_INSTALL ${qm_files_path}/${qm_module}_${lang}*.qm)
			install(FILES ${FILES_INSTALL} DESTINATION ${install_path})
		endforeach()
	endforeach()
endmacro(install_qm_files)

# Install qt qml files

function(install_qml_directory qml_directory install_path)
	message(STATUS "Installing QML directory ${qml_directory}")
	install(DIRECTORY ${qml_directory} DESTINATION ${install_path} PATTERN "*.dll" EXCLUDE PATTERN "*.pdb" EXCLUDE PATTERN "*.so" EXCLUDE PATTERN "*.dylib" EXCLUDE)
endfunction(install_qml_directory)

function(install_qml_plugin qml_plugin_path qml_plugin_name install_path)
	message(STATUS "Installing QML plugin ${qml_plugin_name} from ${qml_plugin_path}")
	if(WIN32)
		set(TMP_BASE_PLUGIN_PATH "${qml_plugin_path}/${qml_plugin_name}")
	else()
		set(TMP_BASE_PLUGIN_PATH "${qml_plugin_path}/lib${qml_plugin_name}")
	endif()
	if(WIN32)
		if(QT_USE_DEBUG_DLL)
			install(FILES "${TMP_BASE_PLUGIN_PATH}.dll" DESTINATION ${TMP_TARGET_DIR} CONFIGURATIONS Release)
			install(FILES "${TMP_BASE_PLUGIN_PATH}d.dll" DESTINATION ${TMP_TARGET_DIR} CONFIGURATIONS Debug)
		else()
			install(FILES "${TMP_BASE_PLUGIN_PATH}.dll" DESTINATION ${TMP_TARGET_DIR})
		endif()
	elseif (APPLE)
		install(FILES "${TMP_BASE_PLUGIN_PATH}.dylib" DESTINATION ${TMP_TARGET_DIR})
	elseif(UNIX)
		install(FILES "${TMP_BASE_PLUGIN_PATH}.so" DESTINATION ${TMP_TARGET_DIR})
	endif()
endfunction(install_qml_plugin)