<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The file "{file}" is not an image.' => 'Файл "{file}" не является изображением.',
  'The image "{file}" height should be "{height}px".' => 'Изображение "{file}" должно быть высотой в {height} пикселей.',
  'The image "{file}" height should be at least "{height}px".' => 'Изображение "{file}" должно быть высотой не меньше чем {height} пикселей.',
  'The image "{file}" height should be at most "{height}px".' => 'Изображение "{file}" должно быть высотой не больше чем {height} пикселей.',
  'The image "{file}" mime type "{mime}" is not allowed.' => 'Изображение "{file}" имеет недопустимый тип "{mime}"',
  'The image "{file}" width should be "{width}px".' => 'Изображение "{file}" должно быть шириной в {width} пикселей.',
  'The image "{file}" width should be at least "{width}px".' => 'Изображение "{file}" должно быть шириной не меньше чем {width} пикселей.',
  'The image "{file}" width should be at most "{width}px".' => 'Изображение "{file}" должно быть шириной не больше чем {width} пикселей.',
  'The image "{file}" small side should be "{side}px".' => 'Меньшая сторона изображения "{file}" должна быть {side} пикселей.',
  'The image "{file}" small side should be at least "{side}px".' => 'Меньшая сторона изображения "{file}" должна быть не меньше чем {side} пикселей.',
  'The image "{file}" small side should be at most "{side}px".' => 'Меньшая сторона изображения "{file}" должна быть не больше чем {side} пикселей.',
  'The image "{file}" big side should be "{side}px".' => 'Большая сторона изображения "{file}" должна быть в {side} пикселей.',
  'The image "{file}" big side should be at least "{side}px".' => 'Большая сторона изображения "{file}" должна быть не меньше чем {side} пикселей.',
  'The image "{file}" big side should be at most "{side}px".' => 'Большая сторона изображения "{file}" должна быть не больше чем {side} пикселей.',
);

